//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jbp.proxy.wsViaIntegration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/Via.Servicio.Entities")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<jbp.proxy.wsViaIntegration.DetalleFactura> DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuntoEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<jbp.proxy.wsViaIntegration.DetalleFactura> Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFacturaField, value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntoEntrega {
            get {
                return this.PuntoEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntoEntregaField, value) != true)) {
                    this.PuntoEntregaField = value;
                    this.RaisePropertyChanged("PuntoEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRegistroField, value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleFactura", Namespace="http://schemas.datacontract.org/2004/07/Via.Servicio.Entities")]
    [System.SerializableAttribute()]
    public partial class DetalleFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoArticulo {
            get {
                return this.CodigoArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoArticuloField, value) != true)) {
                    this.CodigoArticuloField = value;
                    this.RaisePropertyChanged("CodigoArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsViaIntegration.IViaIntegration")]
    public interface IViaIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViaIntegration/CargaFacturasJamesB", ReplyAction="http://tempuri.org/IViaIntegration/CargaFacturasJamesBResponse")]
        bool CargaFacturasJamesB(string user, string password, System.Collections.Generic.List<jbp.proxy.wsViaIntegration.Factura> facturas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViaIntegration/CargaFacturasJamesB", ReplyAction="http://tempuri.org/IViaIntegration/CargaFacturasJamesBResponse")]
        System.Threading.Tasks.Task<bool> CargaFacturasJamesBAsync(string user, string password, System.Collections.Generic.List<jbp.proxy.wsViaIntegration.Factura> facturas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViaIntegrationChannel : jbp.proxy.wsViaIntegration.IViaIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViaIntegrationClient : System.ServiceModel.ClientBase<jbp.proxy.wsViaIntegration.IViaIntegration>, jbp.proxy.wsViaIntegration.IViaIntegration {
        
        public ViaIntegrationClient() {
        }
        
        public ViaIntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViaIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViaIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CargaFacturasJamesB(string user, string password, System.Collections.Generic.List<jbp.proxy.wsViaIntegration.Factura> facturas) {
            return base.Channel.CargaFacturasJamesB(user, password, facturas);
        }
        
        public System.Threading.Tasks.Task<bool> CargaFacturasJamesBAsync(string user, string password, System.Collections.Generic.List<jbp.proxy.wsViaIntegration.Factura> facturas) {
            return base.Channel.CargaFacturasJamesBAsync(user, password, facturas);
        }
    }
}
