<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\jbp.business.hana\jbp.business.hana.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="conf.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>conf.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="conf.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>conf.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>