/*
query diseñado para hana
*/
set schema "SBO_JBP_PROD";

--drop table JB_BI_COSTO_VENTA
select * from JB_BI_COSTO_VENTA

create COLUMN TABLE "JB_VET_PAGO" (
  "id" INTEGER not null primary key GENERATED by default as IDENTITY,
  "DocNumOF" nvarchar(50),
  "codPT" nvarchar(50),
  "productoTerminado" nvarchar(300),
  "lotePT" nvarchar(50),
  "codSemielaborado" nvarchar(50),
  "semielaborado" nvarchar(300),
  "cantidadFabricada" decimal,
  "cantidadRequerida" decimal,
  "codInsumo" nvarchar(50),
  "insumo" nvarchar(300),
  "loteComponente" nvarchar(50),
  "costoUnitarioInsumo" decimal,
  "cantInsumo" decimal,
  "costoTotalLoteFabricado" decimal,
  "cantInsumoPorUnidadPT" decimal,
  "grupoComponente" nvarchar(300),
  "costoInsumo" decimal
);
create COLUMN TABLE "JB_VET_FACTURAS_PAGO" (
  "id" INTEGER not null primary key GENERATED by default as IDENTITY,
  "IdFactura" INTEGER,
  //DATOS ADICIONALES
  "tipoDocumento" nvarchar(50),
  "folioNum" INTEGER,
  "folioNum" INTEGER,
  "folioNum" INTEGER,
  "folioNum" INTEGER,
  "folioNum" INTEGER,
);
