//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emailSender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class conf : global::System.Configuration.ApplicationSettingsBase {
        
        private static conf defaultInstance = ((conf)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new conf())));
        
        public static conf Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rol de Pagos")]
        public string asunto {
            get {
                return ((string)(this["asunto"]));
            }
            set {
                this["asunto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          Estimado Colaborador adjunto encontrará su rol de pagos \r\n          A" +
            "tte.\r\n          James Brown Pharma\r\n        ")]
        public string cuerpoMensaje {
            get {
                return ((string)(this["cuerpoMensaje"]));
            }
            set {
                this["cuerpoMensaje"] = value;
            }
        }
    }
}
